Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

Text_CrystalPC:
	.string "The Red Crystal gave shelter\n"
	.string "to your party.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"
