MtPyre_5F_MapScripts::
	.byte 0


MtPyre_5F_EventScript_Inscription::
# 4 "data/maps/MtPyre_5F/scripts.pory"
	lock
# 5 "data/maps/MtPyre_5F/scripts.pory"
	msgbox MtPyre_5F_Text_WeHopeTheBadKingNeverRecovers, MSGBOX_UNOWNCRYPT
# 6 "data/maps/MtPyre_5F/scripts.pory"
	closemessage
# 7 "data/maps/MtPyre_5F/scripts.pory"
	release
	return


MtPyre_5F_Text_WeHopeTheBadKingNeverRecovers::
# 10 "data/maps/MtPyre_5F/scripts.pory"
	.string "We, the Imprisoners, hope with all\n"
	.string "our heart that the Bad King never\l"
	.string "recover from the tragic confrontation\l"
	.string "with the Good King.\p"
	.string "Its servants, who had weakened the\n"
	.string "Good King, were exhausted, yet almost\l"
	.string "unharmed.\p"
	.string "Our allies, on the other hand, were\n"
	.string "able to wound the Bad King.$"
